### ISSUE TITLE
stb_source_loader.cpp

### ISSUE THREAD

**Issue by zmy1871** [maria-korosteleva/Photographer#2]
Hello, I need to recompile the Photographer.lib, but it seems that this file is missing. Could you kindly provide this file. Thanks in advance
![screenshot-20220517-183534](https://user-images.githubusercontent.com/29728536/168792409-3e7ba305-1e4f-49b0-976a-6fffdcdc3754.png)
！

**Comment by maria-korosteleva** [comment]
Hi @zmy1871 !

This file contains the definitions that are required by stb library, and has the following contents:

```
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb/stb_image_write.h>
```

GitHub doesn't let me attach .cpp files, so, please, create it yourself with the content above 🙂 
Let me know how it goes!

**Comment by zmy1871** [comment]
> Hi @zmy1871 !
> 
> This file contains the definitions that are required by stb library, and has the following contents:
> 
> ```
> #define STB_IMAGE_IMPLEMENTATION
> #include <stb/stb_image.h>
> 
> #define STB_IMAGE_WRITE_IMPLEMENTATION
> #include <stb/stb_image_write.h>
> ```
> 
> GitHub doesn't let me attach .cpp files, so, please, create it yourself with the content above 🙂 Let me know how it goes!

Thanks for your prompt reply!

**Comment by maria-korosteleva** [comment]
I will consider it resolved then =)
